/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import cmsAnalyzer from "@exfabrica/strapi-plugin-awesome-seo/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import generateData from "strapi-plugin-generate-data/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "cms-analyzer": cmsAnalyzer,
    "color-picker": colorPicker,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "strapi-cloud": strapiCloud,
    "generate-data": generateData,
  },
});
